apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  capacity:
    storage: 10Gi # Adjust the size based on your disk
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
      pdName: mydisk
      fsType: ext4
