apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  nodeName: gke-cluster-2-default-pool-e5f12872-906g
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"