apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeName: gke-cluster-1-default-pool-20f54aba-1vtr # schedule pod to specific node
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
